### ISSUE TITLE
Run simulations script broken.

### ISSUE THREAD

**Issue by amoghbl1** [00h-i-r-a00/moby_simulator#15]
As of 85198307a7f93dd9ff7c71d7c947beec5c7bd9da, run_simulations seems to have been broken. Does not launch moby simulator as expected but runs generate messages fine.

Needs investigation or rollback.

**Comment by 00h-i-r-a00** [comment]
Okay, looking into that. I did check multiple simulations manually for this, including a step-by-step pdb trace, and it did seem to be working fine. But lemme look into it.

**Comment by amoghbl1** [comment]
It's not entirely broken, but reading the free memory once to set a limit to the max number of simulation means that some nodes end up having 0 as max limit and nothing runs.

Two ways to solve this would be:
* Set max number of sims to run based on total memory on the machine and use half the total (since thats what we've been advised to do).
* Poll the meminfo file each time you wake up from sleep and schedule number of processes based on that.

Also, we need to reduce the sleep time. sleeping for 30 minutes is not a good idea IMO.
The amount of overheads that run_simulations has isn't too much so performing it once every minute even is a good idea.

**Comment by 00h-i-r-a00** [comment]
So, at the moment, `run_simulations.py` is considering the total memory on the machine so I don't completely understand the

>  reading the free memory once to set a limit to the max number of simulation means that some nodes end up having 0 as max limit. 

part.

I do not think 0 should happen at any time. And actually, it did not when I first scheduled it. Right now, it seems like there is something going on with `/proc/meminfo`. I can't fully identify this, but it seems like there is a difference between `Memory Free` and `Memory Available`. Read [here](https://superuser.com/questions/980820/what-is-the-difference-between-memfree-and-memavailable-in-proc-meminfo). Also, it seems like currently the Free Memory shown by `/proc/meminfo` is lower than Available Memory, which should not happen, and was not happening before when I tested the script. [Here](https://unix.stackexchange.com/questions/440185/why-the-available-memory-is-less-than-the-free-memory-in-free-command) may be one reason. 

I am using `vmstat` statistics now, which seem to be much closer than the ones shown by `htop`, and may suffice as a rough estimate for now. 

I've also added a poll to `vmstat` after every sleep cycle. And tested for 192 simulations for zero threshold, and all of these are showing outputs now, so we no longer have the Uncomplete Simulations for 0 threshold issue. Or the issue of all the simulations not being scheduled.

The only issue thats **left** is that it may be possible that all nodes are not getting equal division of the simuations, I've polled nodes while running the simulations, and they do seem to have an unequal distribution, I don't understand the reason behind that at the moment.

For `sleep time`, I feel like 30 minutes may be a good idea only for 30,000 since one cycle per simulation takes about 20 minutes, right? (including generate_messages.py), but yeah, if we want to poll continuously, thats fine, we could have 1 minute as well. I added that. 

So, now apart from the unequal distribution of jobs, this seems to be running fine for now. Once thats checked, we can probably close the issue.

**Comment by amoghbl1** [comment]
Sounds good. Mark this as fixed when you're done with all the changes.

Also, it would be better if you could commit all changes pertaining to this issue as one commit and use it to close this issue. That way the changes would be easier to track than one commit for smaller changes that all add up to this being fixed.

Something like 11cb51378136077ef7c8c5ed36c488a6fd15f846 can be used to auto close this issue using commit messages.

**Comment by amoghbl1** [comment]
@00h-i-r-a00 I'm guessing this has been fixed, please close the issue if that's the case!

**Comment by 00h-i-r-a00** [comment]
Update:
1. Need to use sleep time as much as the duration of one sets of simulations otherwise simulations tend to overwhelm the servers. This is because a) it takes some time for the simulations to reach their maximum state b) because of RAM consumption not being maximum, the script sees utilizable space, and issues more simulations when it should not.
