### ISSUE TITLE
Results file appended.

### ISSUE THREAD

**Issue by amoghbl1** [00h-i-r-a00/moby_simulator#18]
The results file saving the number of messages delivered every hour is currently appended. So running a test and rerunning it results in a file that has some old results and new ones as well.

This needs to be changes, overwriting the file is one option but maybe saving the file as a backup is a better idea.

**Comment by 00h-i-r-a00** [comment]
It shouldn't have an effect, because the way simulations are currently run is that the results get stored inside the results folder, and then they are transferred to another folder using the `copy_and_delete_simulation_data.sh` script, so every time there are new files being created, even when you rerun the simulations. Of course, we could just create a new results folder named with the configuration number each time, and that might be better, but in that case too the append doesn't really needs to be taken care of.
